[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "vite preview --host 0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
